Agents august updates
aztfmod/rover pull request #281
Opened 2022-08-16 20:21 UTC by LaurentLesle

Update versions
Add node 16 to azdo (still not released yet to docker hub see Issue #280 )
Add kubernetes autoscale support for gihub agent

2022-09-08 03:16 UTC, arnaudlh requested changes
Updates to TF

2022-09-08 03:16 UTC, arnaudlh commented on .env.terraform
> +1.2.7
```suggestion
1.2.9
```

2022-09-08 03:16 UTC, arnaudlh commented on .env.terraform
> +1.3.0-alpha20220803
```suggestion
1.3.0-beta1
```

2022-09-15 02:53 UTC, arnaudlh commented on .env.terraform
> +1.3.0-beta1
```suggestion
1.3.0-rc1
```

2022-09-15 02:53 UTC, arnaudlh approved these changes
LGTM

2022-09-15 06:16 UTC, merged

2022-09-21 14:47 UTC, dsfrederic commented
Why are the azdo agents not released